### ISSUE TITLE
GenericNetworkReceiver refers to non-existent module.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixelAnimations#35]
https://github.com/ManiacalLabs/BiblioPixelAnimations/blob/master/BiblioPixelAnimations/receivers/GenericNetworkReceiver.py#L1

As far as I know, that module has never existed.

**Comment by rec** [comment]
There are other issues in this file, and I'm really not sure what it does anyway.  :-D

**Comment by adammhaile** [comment]
IT's this one: https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/animation/receiver.py#L72
You moved it.

**Comment by rec** [comment]
Oops!  Glad I noticed this.

I'll get to it.
